# Generated by Django 2.1.2 on 2018-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='http451_URLS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urls_to_block', models.CharField(max_length=300, unique=True)),
                ('url_of_authority', models.CharField(max_length=100)),
                ('censorship_reason', models.CharField(max_length=300)),
                ('censorship_title', models.CharField(max_length=100)),
                ('block_by_country', models.BooleanField(default=False)),
                ('country_code', models.TextField(null=True)),
            ],
        ),
    ]
