# Generated by Django 2.1.2 on 2018-11-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http451', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='http451_urls',
            name='censorship_reason',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='http451_urls',
            name='country_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
